### ISSUE TITLE
Add support for MkDocs admonitions

### ISSUE THREAD

**Issue by jewesta** [relimitgmbh/markdown-builder#1]
Support for MkDocs admonitions should be added. Admonitions are notices rendered as text in a box along with a status icon.

```
!!! note

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et euismod
    nulla. Curabitur feugiat, tortor non consequat finibus, justo purus auctor
    massa, nec semper lorem quam in massa.
```

https://squidfunk.github.io/mkdocs-material/reference/admonitions/

**Comment by AndreaUhl90** [comment]
PR is merged so this issue can be closed.
