### ISSUE TITLE
Make default heading style configurable

### ISSUE THREAD

**Issue by jewesta** [relimitgmbh/markdown-builder#3]
Markdown Builder currently uses underline (Setext) headings:
```
Heading
======
```
And only switches to hashtag (Atx) style headings from level 3+
```
# Heading
```
This can be set on individual `Heading` elements, but not with the builder pattern and it cannot be changed globally via `MarkdownSerializationOptions`.

Adding this to the builder is probably not such a good idea. Should the need arise to change this then it will surely be required to apply globally, for the whole markdown document.

**Comment by AndreaUhl90** [comment]
PR merged, so this issue can be closed.
