### ISSUE TITLE
Fix broken indentation system

### ISSUE THREAD

**Issue by jewesta** [relimitgmbh/markdown-builder#7]
While working on #1 I noticed that the indentation system is broken. Most of the code assumed that indentation levels needed to be one higher than that of the parent indentation level. When in reality the parent elements each added one indentation level and children only needed to decide wether they needed to add one further level or stay on the same. Through some weird compensation effect this bug wasn't obvious at first as long as the level was never changed.

**Comment by AndreaUhl90** [comment]
PR is merged so this issue can be closed.
